[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/k8s-infra

[all]
; k8s-master-1 ansible_host=192.168.20.111
; k8s-master-2 ansible_host=192.168.20.112
; k8s-master-3 ansible_host=192.168.20.113
; k8s-worker-1 ansible_host=192.168.20.121
k8s-worker-2 ansible_host=192.168.20.122
; k8s-worker-3 ansible_host=192.168.20.123

[kube_control_plane]
k8s-master-1
k8s-master-2
k8s-master-3

; [etcd]
; k8s-master-1
; k8s-master-2
; k8s-master-3

[kube_node]
; k8s-worker-1
k8s-worker-2
; k8s-worker-3

; [loadbalancer]
; k8s-master-1
; k8s-master-2
; k8s-master-3

[k8s_cluster:children]
; kube_control_plane
kube_node